Attribute VB_Name = "modOptionsConst"
'@Folder "State.Constants"
Option Explicit

Public Const DO_SHOW_ORPHAN_STATES As String = "DO_SHOW_ORPHAN_STATES"
Public Const DO_ASSOCIATE_ORPHAN_STATES As String = "DO_ASSOCIATE_ORPHAN_STATES"
Public Const DO_SHOW_PARTIAL_MATCH As String = "DO_SHOW_PARTIAL_MATCH"
Public Const DO_HIDE_NONMATCH_COLS As String = "DO_HIDE_NONMATCH_COLS"
Public Const DO_ALLOW_APPLY_PARTIAL_MATCH As String = "DO_ALLOW_APPLY_PARTIAL_MATCH"
Public Const DO_SHOW_NONMATCHING_COLS As String = "DO_SHOW_NONMATCHING_COLS"
Public Const DO_SEARCH_CASE As String = "DO_SEARCH_CASE"
Public Const DO_SEARCH_WHOLE As String = "DO_SEARCH_WHOLE"
Public Const DO_CLOSE_ON_APPLY As String = "DO_CLOSE_ON_APPLY"
